### ISSUE TITLE
Segunda Reunião - Andamento das Atividades

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#11]

**Comment by gabrielrudan** [comment]
Nessa reunião, ficamos de verficar o andamento das atividades separadas após a primeira reunião, além de definir o apresentar da Segunda Entrega, e outras coisas...

**Comment by zairobastos** [comment]
@gabrielrudan coloca o print da reunião

**Comment by gabrielrudan** [comment]
**Registro da Segunda Reunião**


![](https://media.discordapp.net/attachments/1162369405783646248/1181620847505575996/Captura_de_tela_2023-12-02_142653.png?ex=6581b92b&is=656f442b&hm=1de880bd4994c4f609211977ba5b90fc00a555948e7775f5023b2a86d3df9cdc&=&format=webp&quality=lossless&width=1079&height=604)
