### ISSUE TITLE
Análise Exploratória dos Dados

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#4]

**Comment by gabrielrudan** [comment]
Realizar uma exploração detalhada dos datasets fornecidos, identificando padrões, distribuições, valores ausentes e potenciais desafios na construção do classificador de sentimentos.

**Comment by zairobastos** [comment]
- [x]  Identificando padrões
- [x] Distribuições
- [x] Valores ausentes
- [x] Potenciais desafios na construção do classificador de sentimentos
