### ISSUE TITLE
Seleção, Treinamento e Otimização de Algoritmo

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#5]

**Comment by gabrielrudan** [comment]
Explorar diferentes algoritmos de classificação de sentimentos, como SVM, Naive Bayes ou redes neurais, e selecionar o mais adequado ao problema. Realizar o treinamento do modelo escolhido e otimizar seus hiperparâmetros para obter a melhor performance possível.

**Comment by zairobastos** [comment]
- [x] SVM
- [x] Naive Bayes
- [x] Redes Neurais
- [x] Treinar modelo
- [x] Otimizar hiperparâmetros
