### ISSUE TITLE
Análise de Importância de Variáveis e Interpretabilidade

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#6]

**Comment by gabrielrudan** [comment]
Caso o modelo permita, realizar uma análise de importância de variáveis, identificando quais palavras ou termos têm maior influência na classificação de sentimentos. Além disso, buscar formas de tornar o modelo mais interpretable, a fim de entender como ele toma suas decisões.

**Comment by zairobastos** [comment]
- [x] Realizar uma análise de importância de variáveis
- [x] Identificando quais palavras ou termos têm maior influência na classificação de sentimentos
- [x] Tornar o modelo mais interpretable, a fim de entender como ele toma suas decisões
