### ISSUE TITLE
Validação dos Resultados e Performance do Algoritmo

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#7]

**Comment by gabrielrudan** [comment]
Realizar uma validação robusta do modelo utilizando técnicas como validação cruzada, matriz de confusão e curvas de aprendizado para avaliar sua capacidade de generalização e performance.

**Comment by zairobastos** [comment]
- [x] Validação cruzada
- [x] Matriz de confusão
- [x] Curvas de aprendizado para avaliar sua capacidade de generalização e performance
