### ISSUE TITLE
Documentação no Repositório GitHub

### ISSUE THREAD

**Issue by gabrielrudan** [zairobastos/moodgram#8]

**Comment by gabrielrudan** [comment]
Todo o trabalho deve ser documentado em um repositório GitHub dedicado ao projeto. A documentação deve incluir explicações detalhadas dos passos executados, gráficos e visualizações para ilustrar os resultados, além de qualquer outra informação relevante para entender o processo de desenvolvimento do modelo.

**Comment by zairobastos** [comment]
- [ ] Incluir explicações detalhadas dos passos executados
- [ ] Gráficos
- [ ] Visualizações para ilustrar os resultados
- [ ] Além de qualquer outra informação relevante para entender o processo de desenvolvimento do modelo
